### PR TITLE
Remote events

### PR DESCRIPTION
**Pull request by tshoppa**
Publishing user interaction events for remote navigation services (such as http://sozi-remotifier.glitch.me/)

### CODE REVIEW

**Comment by aumouvantsillage** [comment]
If I remember well, you told me that you introduced the "localChange" event to prevent circular event triggering.
My problem is that I do not really understand why this would happen.
It would be great if you could give me an example that motivates your choice.

My preference would be to emit `moveToFrame`, `jumpToFrame` ... events from the `Player` class itself. It would feel less redundant and it would help cover other use cases than keyboard and mouse actions. For instance, at the moment, the `localChange` event is not emitted if the player is controlled by the presenter console (please correct me if I'm wrong).

**Comment by tshoppa** [comment]
In the remote control scenario, circular events may occur, when two or more master presentations (i.e. sozi presentations, that are capable of receiving and sending remote signals) are active at the same time.
If we now use the same function to process a remote event as well as sending a remote event, the two master instances will start an endless game of informing the other, that "something just happened".

Example `jumpToFrame` and two master presentations A and B 

-  Presenter at A jumps to Frame x
- A.jumpToFrame processes jump and fires event ("jumpedTo(x)")
- B receives remote event ("jumpedTo(x)"), B.jumpToFrame processes jump and **again** fires "jumpedTo(x)"
- A receives remote event, processes and fires.... and so on.
simple

While this particular case can easily be filtered out (_do nothing, if we are already at frame x_), there are more tricky scenarios:

- **race conditions** two jump commands may intersect and two masters start juggling with two balls. This is reproducable even if both inital commands are sent from the same master. E.g. Jump to next and back again immediately. If the second jump is done faster than the network roundtrip of the first, the system is trapped. 
crossing

- **automated transitions** will be started on both masters, once the first frame of the sequence is reached. Both of them start firing change events may lead to a race condition again.

A way to prevent this is to distinguish between user driven changes and system changes. In MVC this would be changes applied through the controler vs changes applied directly to the model (or within the model). 

I think remote events should be tied to the controler, not to the model. Internal model changes will be performed at the client anyway, so there is no need to propagate them (e.g. all the internal calls to pause() in the player mustn't be transfered explicitly).

As Sozi does not implement a strict separation of MV(C), I found keyboard/mouse listeners to be the most direct choice. 

All that said I 100% understand, that it does not feel very well designed. And you're also right, that it does not work with the presenter console. It would require to move the localChange event emission to `player.moveToNext()` which is also used in automated frame transition with the side effects described above.

One approach would be to implement a thin explicit controler in module `player`  which reorganizes some of the code.
Alternatively I thought about restricting remote sessions to one master only. But this would still leave conflicts in automated transitions (master and client trying to do the same thing).

**Comment by aumouvantsillage** [comment]
Thanks a lot for taking the time to write such a detailed explanation.

> But this would still leave conflicts in automated transitions (master and client trying to do the same thing).

From my point of view, in a "client" presentation, automatic transitions should be disabled.

> One approach would be to implement a thin explicit controler in module player which reorganizes some of the code.

I totally agree with this solution.
I assume that in most cases, there will be only one master presentation, but maybe one could imagine a valid use case for the multiple-master situation.

**Comment by tshoppa** [comment]
I went into a bunch of approaches the last weeks, but I am struggling. Mainly, because I am not sure about what you need to feel good about the solution. What I understood is, that you would like to remove redundancy (in the sense of code replication/duplication). Additionally we need something centralized to capture events from keyboard, mouse, presenter console and touchGestures likewise. 
Here are my approaches, the pros and cons. I am not sure which path to follow and would really appreciate your recommendation.

- **single master setup**. Least impact on sozi core, but tricky otherwise. First of all, handle mutliple master registrations. Recommended strategy is to always accept the latest registering master, because it is the one that is most probably alive and kicking (while the former might have died unusually and unnoticed). However, this requires the option to "clientify" a master, in case the former are still working. And this soluton will produce a lot of events/network traffic. All in all it feels like a lot of effort to rather restrict than to invent.
- **explicit controller** As Sozi is implemented rather in components than in layers, I would add a controller to each affected class. [Here is an implementation for player](https://github.com/tshoppa/Sozi/blob/new-remote-events/js/player/Player.js). It would need the same for viewer.   While it more or less just splits the player code into two classes, it also installs some _fassade_ methods which will then include the event code (not implemented yet) and might feel as superfluous as the repitative "local events".  I was in doubt if this meets your expactions. (It will provide a central entrance for user interaction though).
- **UI awareness** Last thing I tried was to somehow preserve the information, that a change is based on user interaction down to the very basic method, where  the change is actually performed. E.G. all _moveTo..._ methods will finally end in _moveToFrame()_, where the event can be raised. This will reduce the amount of explicit event firing code  significantly. But it will add additional parameters [see here for an example](https://github.com/tshoppa/Sozi/blob/transaction-remote-events/js/player/Player.js) or some other mechanism of equal extend which might feel like replacing one flaw with another.

Personally I would opt for solution 2, but I would follow any track you advice.

**Comment by aumouvantsillage** [comment]
> Personally I would opt for solution 2, but I would follow any track you advice.

After looking at your explit controller implementation, I think that I would do exactly the same, keeping the essential methods in Player and handling "moveToFirst", "moveToNext", etc in the Controller.

> it also installs some fassade methods which will then include the event code (not implemented yet) and might feel as superfluous as the repitative "local events"

I think there will be less redundancy with this architecture. And the facade methods will prevent tying local events to specific user events, so this is OK for me.

**Comment by aumouvantsillage** [comment]
By the way, I am considering some changes in the build process with two main purposes: making the build faster and possibly using other tools to package Sozi.
There will be some changes in the directory structure but no major changes in the JavaScript itself.

**Comment by tshoppa** [comment]
thanks for your recommendation! I followed the path and also added a controller to the viewport and fixed some stuff. This version is now commited [to the new-remote-events branch](https://github.com/tshoppa/Sozi/tree/new-remote-events). 
While coding, I found that there are some dependencies between player and viewport which indicate, that both controller might as well belong together. (e.g.  viewport keyboard events have to be routed through player, some constants like SCALE_FACTOR are double defined). So I created a [second version with a single UIController instance](https://github.com/tshoppa/Sozi/tree/single-controller). It worked out quite straightforward and will probably eliminate the need for some viewport events (dragStart, dragEnd) when done (there are some adoptions tbd). 
What do you think?

**Comment by aumouvantsillage** [comment]
Thanks. I think I'll have some time during this week-end to review and integrate your changes.

I have just updated the master branch with a new build script using Gulp instead of Grunt.
One benefit of the change is that now, you can build and run Sozi without packaging it.

If you want to give it a try, you will need to pull the latest changes, install Gulp and run `npm install`.
Then use these two commands to build the electron app and run it:

```
gulp
npm start
```

**Comment by tshoppa** [comment]
I think integration is fine with the ["deidcated controller" version](https://github.com/tshoppa/Sozi/tree/new-remote-events). The [single controller](https://github.com/tshoppa/Sozi/tree/single-controller) would still neeed some adoptions - I would slightly prefer it though because I think it adds some benefits beyond the remote stuff. Of course, I would really welcome you to support here, (e.g. at commenting in the context of clipping... I am not sure If I really understood whats going on here :-)) 
I am looking forward to try out the gulp stuff! Nice! You are quite active currently, aren't you? I saw you also moved the  user forum to github - (good decision from my point of view). Maybe we should shift some  content from the old forum here? Like the links to example presentations, which I always found useful.

**Comment by tshoppa** [comment]
I tried gulp, but couldn't manage to get it run properly.  Here's what I tried and where I stuck:

- **windows native:** npm install shows error "unsupported platform" for darwin and linux, also "gulp all" fails for a missing "electron-installer-debian" module. That's obvious for windows, however, I could not narrow the target to win32 only. Same errors, even if I edit sozi-default.json ("platform": ["win32"], "arch": ["x64"]). Somehow it seemd to be ignored.

- Switched to **WSL2, debian 10**. After some fiddling with a proper Nodes Version (Now V14) and dependencies I could run "gulp all". But it takes 20-30min to complete.

- Changed config again to a single platform, however, now I get an AssertionError `AssertionError [ERR_ASSERTION]: One or more tasks should be combined using series or parallel
    at normalizeArgs (D:\projekte\Sozi\Sozi\node_modules\undertaker\lib\helpers\normalizeArgs.js:28:3)
    at Gulp.parallel (D:\projekte\Sozi\Sozi\node_modules\undertaker\lib\parallel.js:13:14)
    at makeElectronDebianTasks (D:\projekte\Sozi\Sozi\gulpfile.js:427:12)` 
    (I can provide the complete stacktrace if needed)

So, there seem to be a problem with the config files.  
I also had a nice target set up in grunt, wich just builds the templates and a batch to copy the templates with updated js into the windows dist directory. This works in seconds. maybe I can bring it to gulp, but for the moment I would like to switch back to grunt. 
I think that would need some adoption due to the changed directory structure?

**Comment by aumouvantsillage** [comment]
Thanks for your feedback.
Actually, I was not expecting `gulp all` to work on Windows.

> I also had a nice target set up in grunt, wich just builds the templates and a batch to copy the templates with updated js into the windows dist directory. This works in seconds. maybe I can bring it to gulp

Yes. But this is exactly the purpose of these two commands:

```
gulp
npm start
```

They are supposed to build and run Sozi without packaging it.
`gulp` (without `all`) takes 12 seconds on my computer.

**Comment by aumouvantsillage** [comment]
I have pushed some fixes to `package.json` and `gulpfile.js`:

* `electron-installer-debian` and `electron-installer-redhat` are now optional dependencies. When building on Windows, `npm install` will ignore them.
* The Gulp tasks for Linux packaging are disabled when the target plaforms do not include `linux`.

I  have made it work successfully in a Windows VM, building Sozi with a config file that contains only the `win32` platform:

```
SOZI_CONFIG=sozi-windows-x64 gulp
npm start
```

N.B. For some reason, npm did not create the `node_modules/.bin` folder on my first attempt. I had to delete `node_modules` and rerun `npm install`.

**Comment by aumouvantsillage** [comment]
I have merged the "dedicated controllers" version manually, with a few changes.
In my version, Viewport is no longer an event emitter. All viewport-related events are emitted by its controller.
I did no see the point of calling `this.viewport.emit()` in the viewport's controller.

In `Player.js`, is it still relevant to emit `localChange` events with the event name in the argument?
I would expect the controller to emit `jumpToFrame` events directly, possibly with `{local: true}` if it is needed.

**Comment by aumouvantsillage** [comment]
I am merging the single controller version.
I think that the class name `UIController` is not specific enough, compared to the other `Controller` class used in the editor.
Do you think that something like `PlayerFacade` would be appropriate? I am not familiar with the Facade design pattern so maybe this is a bad choice.

**Comment by tshoppa** [comment]
Ok, trying to catch up a little. Sorry for my late reply, my job keeps me super busy at the moment. I really appreciate your commitment and I feel a little guilty. 
Now first of all, gulp works like a charm with your modifications! Great step forward, builds in seconds. Super!
I also tried to get ahead with the single controller last weekend, but I was a stuck in a bunch of dependencies which I didn't dare to resolve. I felt I would  actually need to understand the functionallity and design behind it and didn't had the time to dig deeper :-( 
So, from my current perspective, let's just accept the dedicates controllers for now. It is easy to understand and more of a refactoring than a change in design. (I hate redundancies, though, but I am obsessive with this, so don't pay too much attention to my malaise :-))
That said and to answer your question: I would always call a class by a) what it is doing (action) , b) what is it's purpose (objective) or c) what is it's responsibility (position).
Patterns my give a hint (factory, abstract, ... ) but often do not (delegate, facade, ...) because these just describes a techinque. 
(You would rather like to buy a cake from a Confectioner, and not from an "institution building food created with fat and sugar" wouldn't you? :-)) 
So in this case, I would have a look at what in particular is the difference between the "UIController" and the "Controller" class. Maybe it is "ShowController" vs. "EditorController"  or something like that? Sorry, I just don't have insight enough to make better suggestions, but I hope you got the idea.

**Comment by aumouvantsillage** [comment]
> Ok, trying to catch up a little. Sorry for my late reply, my job keeps me super busy at the moment.

No problem. I can understand that :smiley: 

> So, from my current perspective, let's just accept the dedicates controllers for now.

Actually, I have already pushed a single-controller implementation inspired by yours.
I have made a few simplifications: for instance, the controller no longer listens to its own events.
I will review the code and test it again to make sure there were no regressions.

> Maybe it is "ShowController" vs. "EditorController" or something like that?

At some point, I felt that "Controller" was too general.
But at second thought, I think I would  choose `PlayerController`.

Thanks for taking the time to answer.

One last thing. Maybe you missed another question in one of my previous messages: in `Player.js`, is it still relevant to emit `localChange` events with the event name in the argument? I would expect the controller to emit `jumpToFrame` events directly, possibly with `{local: true}` if it is needed.

**Comment by tshoppa** [comment]
> At some point, I felt that "Controller" was too general.
> But at second thought, I think I would choose `PlayerController`.

Yes, that makes sense. I perceive all the classes of the player module (like Viewer, FrameList etc.) as a tight composite which form the "player" (the thing that displays the presentation). So it totally makes sense to share a common controller which is the "PlayerController".

> 
> One last thing. Maybe you missed another question in one of my previous messages: in `Player.js`, is it still relevant to emit `localChange` events with the event name in the argument? I would expect the controller to emit `jumpToFrame` events directly, possibly with `{local: true}` if it is needed.

Yes, I missed that!  I am not sure which place in the code you are referring to. I couldn't spot a localChange event in Player.js (neither in my local single-controller branch nor in sozi master, but maybe I lost track on the branches ). Anyway - Player should not emit any localChange events, it should be emitted in PlayerController.js only (I mean, that's why we started all this, didn't we :-))

I would follow the [pattern in single controller branch ](https://github.com/tshoppa/Sozi/blob/single-controller/js/player/UIController.js) 
`jumpToFrame(frame){
        let f = this.player.findFrame(frame);
        this.emit("localChange", {change:"jumpToFrame", value:f});
        this.player.jumpToFrame(f);
    }  `

Concerning the parameter - again I am not sure what you refer to by `{local: true}` - maybe this is from a branch where I propagated the "local" aspect down into player (with optional parameter "local")? This would be completely obsolete here.

Hope I could help you.  One last remark: I totally love Sozi and what can be achieved with it. I believe the open canvas pattern is a superior narrative paradigm compared to deck oriented presentations. I use it, whenever I feel that storytelling is important (like in pitches, talks, keynotes etc.). And I push the idea behind it whenever I can (especially at my workplace, which btw is part of BNP Paribas - you might have heard of that ...:-)). So - I wanted to say thank you to bring up such a gem!

I would like to contribute more when I have more time again.

**Comment by aumouvantsillage** [comment]
> I couldn't spot a localChange event in Player.js

Indeed. I meant "in `PlayerController.js`"
So my question is: why not write this?

```js
jumpToFrame(frame){       
    let f = this.player.findFrame(frame);
    this.emit("jumpToFrame", f);
    this.player.jumpToFrame(f);
}
```

Or if you really need to distinguish two kinds of `jumpToFrame` events:

```js
jumpToFrame(frame){       
    let f = this.player.findFrame(frame);
    this.emit("jumpToFrame", {local: true, value: f});
    this.player.jumpToFrame(f);
}
```

Thanks for your kind words and for your support.
Until now, I have developed Sozi mostly alone. It's the first time that I receive such a big contribution and it's an interesting challenge.

**Comment by tshoppa** [comment]
> It's the first time that I receive such a big contribution and it's an interesting challenge.

I read this like "curse and blessing of team work" - you get some help - but you constantly have to grapple with different perspectives :-D 

Concerning your question: Yes, good idea! Since we now register at a controller, it is inherently clear that the events are of some kind of user interaction nature. No need to tag it in the event type anymore.  
If we do this for all the (former) local events, (like "blankscreen", "pause" etc.) it is much easier for consumers to distinguish the actual action (no switch needed anymore). Maybe we can update the tag "interactive" at the same time? I never liked it. Either by the actual action ("rotate", "zoom", "translate") or by some more concrete term like "moveCamera" or sth. 

Nice, i like it! See, you updated my perspective :-)

**Comment by aumouvantsillage** [comment]
Thanks for your feedback.
I will make those changes soon.

I also suggest that we close this pull request and continue this conversation in the [Discussions](https://github.com/sozi-projects/Sozi/discussions) forum.

**Comment by aumouvantsillage** [comment]
The last few commits introduce the following changes:
* the controller class for the player has been renamed to `PlayerController`
* `localChange` events have been renamed, using the name of the methods that emits them.

**Pull request closed without merging**
